const mongoose = require('mongoose');
const { Schema } = mongoose;

const promo = new Schema({
    esPromocion: { type: Boolean },
    cantidad: { type: Number },
    cantidadDisponible: { type: Number },
    cantidadPromoVendidas: { type: Number },
    cantLlevar: { type: Number },
    cantPagar: { type: Number },
    categoria: { type: String },
    date: { type: Date, default: Date.now },
    descripcion: { type: String },
    descripcionPromocion: { type: String },
    descuento: { type: Number },
    emailDuenoEcommerce: { type: String },
    empresa: { type: String },
    endPointsIdTokens: { type: String },
    fechaFin: { type: Date },
    fechaInicio: { type: Date },
    idCliente: { type: String },
    idOwner: { type: String },
    idProd: { type: String },
    moneda: { type: String },
    nombreEcommerce: { type: String },
    nombreProducto: { type: String },
    nombreProd: { type: String },
    nombrePromocion: { type: String },
    pathImg: [{ type: String }],
    pathImgs: [{ type: String }],
    promoLink: { type: String },
    precio: { type: Number },    
    precioFinal: { type: Number },
    precioInicial: { type: Number },
    promoVencida: { type: Boolean },
    rutaSimple: { type: String },
    rutaSimple2: { type: String },
    rutaSimpleImg: [{ type: String }],
    rutaURL: { type: String },
    rubro: { type: String },
    titulo: { type: String },
    urlImg: [{ type: String }],
});

module.exports = mongoose.model('promo', promo);
